spring:
  application:
    name: jwt-memory

jwt:
  secret: "mi_clave_super_secreta_de_al_menos_32_caracteres_123456"
  accessExpiration: 120000 # 2 minutos (ms)
  refreshExpiration: 604800000    # 7 días
